apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: snapshot
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
